highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    lineNumbersInTable: true
    noClasses: false #necessary configuration

goldmark:
    extensions:
        definitionList: true
        footnote: true
        linkify: true
        strikethrough: true
        table: true
        taskList: true
        typographer: true
        
    renderer:
        unsafe: false

tableOfContents:
    startLevel: 2
    endLevel: 6