description: "Mes aventures et découvertes dans le domaine du développement web, de l'administration système, de la sécurité, et de la généalogie."
keywords: ["développement web", "administration système", "généalogie"]

app:
    title: "Blog de William Blondel"
    noFavicon: false
    svgFavicon: ""
    themeColor: "#ffffff"
    iconColor: "#5bbad5"
    tileColor: "#da532c"

footer:
    enable: true
    custom: ''
    hugo: true
    copyright: true
    author: true
    since: 2021
    license: '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.fr" target="_blank">CC BY-NC-SA 4.0</a>'

header:
    desktopMode: "fixed"
    mobileMode: "auto"
    
    title:
        logo: ""
        name: "Blog de William Blondel"
        pre: ""
        post: ""

home:
    rss: 10
    
    profile:
        enable: true
        title: "William G. Blondel"
        subtitle: "Né geek avec un Amstrad CPC 6128. Développeur web, administrateur système, et généalogiste amateur."
        gravatarEmail: "contact@williamblondel.fr"
        social: true
        disclaimer: ""
    
    posts:
        enable: true
        paginate: 6

timeAgo:
    enable: true
    lang: fr
