# If a config block has at least one setting that changes depending on the
# current language, the whole block is in the corresponding config file
# (ie params.en.yaml)

# uBlogger theme version
version: "2.0.X"

# site default theme ("light", "dark", "auto")
defaultTheme: "auto"

#public git repo url only when enableGitInfo is true
gitRepo: "https://github.com/wblondel/williamblondel.fr"

# ("sha256", "sha384", "sha512", "md5")
fingerprint: "sha512"

# date format
# TODO: Multilang
dateFormat: "2006-01-02"

analytics:
    enable: false

    google:
        anonymizeIP: true

compatibility:
    polyfill: true
    objectFit: true
    
list:
    paginate: 20
    dateFormat: "01-02"
    rss: 10

page:
    theme: classic
    hiddenFromHomePage: false
    hiddenFromSearch: false
    hiddenFeatureImage: false
    twemoji: true
    lightgallery: false
    ruby: true
    fraction: true
    linkToMarkdown: true
    rssFullText: false
    
    math:
        enable: false
    
    code:
        copy: true
        maxShownLines: 10
        
    share:
        enable: true
        Twitter: true
        Facebook: true
        Evernote: true

search:
    enable: true
    type: "lunr"
    contentLength: 4000
    placeholder: ""
    maxResultLength: 10
    snippetLength: 30
    highlightTag: "em"
    absoluteURL: false
    
# Section (all posts) page config
section:
    paginate: 20
    dateFormat: "01-02"
    rss: 10 # number of posts in RSS feed

social:
    Github: wblondel
    LinkedIn: wgblondel
    Twitter: wgblondel
    Instagram: wgblondel
    Telegram: wblondel
    Reddit: wblondel
    Spotify: william78
    Steam: wgblondel
    #Skype: w.blondel
    RSS: true
