description: "My adventures and findings about web development, system administration, security, and genealogy."
keywords: ["web development", "system administration", "genealogy"]

app:
    title: "Blog of William Blondel"
    noFavicon: false
    svgFavicon: ""
    themeColor: "#ffffff"
    iconColor: "#5bbad5"
    tileColor: "#da532c"

header:
    desktopMode: "fixed"
    mobileMode: "auto"
    
    title:
        logo: ""
        name: "Blog of William Blondel"
        pre: ""
        post: ""

home:
    rss: 10
    
    profile:
        enable: true
        title: "William G. Blondel"
        subtitle: "Born geek with an Amstrad CPC 6128. Web developer, system administrator, and amateur genealogist."
        gravatarEmail: "contact@williamblondel.fr"
        social: true
        disclaimer: ""
    
    posts:
        enable: true
        paginate: 6

footer:
    license: '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'

timeAgo:
    enable: true
    lang: en